name: mazes
description: The most complete offline maze puzzle app.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  maze_core:
    path: ../../packages/maze_core
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
